#!/usr/bin/env python3
import argparse


def get_argparse():
    parser = argparse.ArgumentParser(description='This is for defining the location of SNV in iMiGseq')
    parser.add_argument('-s', '--save_path', type=str, default="./",
                        help='path/to/snp (the path to snp folder generated by VAULT)')
    parser.add_argument('-v', '--vcf_file', type=str, required=True, help='vcf file')
    parser.add_argument('-g', '--gene_file', type=str, required=True, help='gene file')
    parser.add_argument('-o', '--output_file', type=str, required=True, help='output file')
    return parser.parse_args()


def get_location(args):
    gene_feature = args.gene_file
    vcf = args.vcf_file
    outfile = args.output_file

    with open(gene_feature, 'r') as gene_feature, open(vcf, 'r') as vcf, open(outfile, 'w') as outfile:

        gene_feature_dir = {}
        for line in gene_feature:
            line_split = line.strip().split("\t")
            key = line_split[3].strip()
            value = line_split[1] + ' ' + line_split[2]
            gene_feature_dir[key] = value.strip()

        for line in vcf:
            if not line.startswith("#"):
                pos = int(line.split("\t")[1])
                location = [key for key in gene_feature_dir if int(gene_feature_dir[key].split()[0]) <= pos <=
                            int(gene_feature_dir[key].split()[1])]
                if len(location) == 0:
                    location = ["Intergenic"]
                outfile.writelines(" ".join(location) + '\t' + line)


if __name__ == '__main__':
    args = get_argparse()
    get_location(args)
